apiVersion: v1
kind: Service
metadata:
  name: opentelemetrydemo
  namespace: opentelemetrydemo
spec:
  selector:
    app: opentelemetrydemo
    tier: backend
  type: NodePort
  ports:
    - port: 5432
      nodePort: 33000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetrydemo
  namespace: opentelemetrydemo
spec:
  selector:
    matchLabels:
      app: opentelemetrydemo
      tier: backend
  replicas: 1
  template:
    metadata:
      namespace: opentelemetrydemo
      labels:
        app: opentelemetrydemo
        tier: backend
    spec:
      containers:
        - name: opentelemetrydemo
          image: localhost:32000/opentelemetrydemo:<version>
          ports:
            - name: http
              containerPort: 8080